# File: templates/database-build.yml

jobs:
- job: ${{parameters.name}}
  pool: 
    vmImage: ${{parameters.vmImage}}
  steps:
  - task: MSBuild@1
    inputs:
      solution: '${{projectPath}}/${{parameters.project}}.sqlproj'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '${{projectPath}}/${{parameters.project}}/bin/Debug/'
      contents: '*.dacpac' 
      targetFolder: $(build.artifactstagingdirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: '${{parameters.project}}-dacpac' 
      publishLocation: 'container'
      targetPath: 'drop'