# File: templates/database-build.yml

jobs:
- job: ${{parameters.name}}
  pool: 
    vmImage: ${{parameters.vmImage}}
  steps:
  - task: MSBuild@1
    inputs:
      solution: '${{parameters.projectPath}}'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '${{parameters.buildPath}}'
      contents: '*.dacpac' 
      targetFolder: '${{parameters.artifactstagingdirectory}}'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '${{parameters.artifactstagingdirectory}}'
      artifactName: '${{parameters.artifactName}}' 
      publishLocation: 'container'
      targetPath: 'drop'