# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self

parameters:
  projectName: 'Company.Solution.Database'

jobs:
- template: templates/database-build.yml
  parameters:
    name: Log
    vmImage: 'vs2017-win2016'
    project: '$(projectName)'
    projectPath: '**/$(projectName).sqlproj' 
    buildPath: '**/*[Bn]in/*[Dd]ebug/'
    artifactstagingdirectory: $(build.artifactstagingdirectory)
    artifactName: '$(projectName)-dacpac'
